@@grammar :: fccn
@@whitespace :: /[\t ]+/
@@eol_comments :: /#.*?$/

start = '\n'.{statement | () } $;
statement = input:wireset '->' ~ action:combinator '->' output:wireset ;
wireset = wire [',' wire] ;
wire::Wire = name:identifier;
combinator = arithmetic | decider ;

decider::Decider = left:argument op:logiop ~ right:argument ':' result:deciderout ;
deciderout = signal:identifier value:['(1)'] ;
logiop = '>' | '>=' | '=' | '!=' | '<=' | '<' ;

arithmetic::Arithmetic = result:identifier '=' ~ left:argument op:arthop right:argument ;
arthop = '+' | '-' | '*' | '/' | '%' | '>>' | '<<' ;

argument = identifier | number ;

@name
identifier = /[a-zA-Z_][0-9a-zA-Z_]*/ ;
number::int = /[0-9]+/ ;
